[Resolve]
DNS=8.8.8.8 #1.1.1.1 #223.5.5.5#dns.alidns.com 9.9.9.9#dns.quad9.net
FallbackDNS=119.29.29.29#dot.pub 1.1.1.1#cloudflare-dns.com
DNSOverTLS=yes
DNSSEC=allow-downgrade
Cache=yes

LLMNR=no
MulticastDNS=yes

