#!/bin/bash
# Script: setup_domain_policy_routing.sh
# Purpose: Route traffic to specific domains via a custom interface (wlp3s0)
# using dnsmasq + ipset + iptables + policy routing.
# Author: Generated for user request

set -euo pipefail   # Strict mode: exit on error, undefined var, pipe failure

# --------------------- CONFIGURATION VARIABLES ---------------------
# Modify these according to your network
IPSET_NAME="google_ips"              # Name of the ipset
DOMAINS="google.com youtube.com github.com"  # Domains to route via Wi-Fi
UPSTREAM_DNS="8.8.8.8"               # Upstream DNS server for dnsmasq
WIFI_IF="wlp3s0"                     # Interface for the special route
WIFI_GW="192.168.178.254"            # Gateway IP of wlp3s0
TABLE_ID=100                         # Custom routing table ID
TABLE_NAME="mytable"                 # Name of the custom table (in /etc/iproute2/rt_tables)
FW_MARK=1                            # Firewall mark value

# Derived paths
DNSMASQ_CONF_DIR="/etc/dnsmasq.d"
DNSMASQ_POLICY_CONF="${DNSMASQ_CONF_DIR}/99-policy-routing.conf"
RT_TABLES_FILE="/etc/iproute2/rt_tables"

# --------------------- FUNCTION DEFINITIONS ---------------------

# Check if script is run as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        echo "ERROR: This script must be run as root (use sudo)." >&2
        exit 1
    fi
}

# Create the ipset if it doesn't already exist
create_ipset() {
    if ! ipset list "$IPSET_NAME" &>/dev/null; then
        echo "Creating ipset: $IPSET_NAME (type hash:ip)"
        ipset create "$IPSET_NAME" hash:ip
    else
        echo "ipset $IPSET_NAME already exists. Skipping creation."
    fi
}

# Configure dnsmasq to resolve domains and add IPs to the ipset
configure_dnsmasq() {
    # Create dnsmasq drop-in directory if missing
    mkdir -p "$DNSMASQ_CONF_DIR"

    # Write configuration file (overwrites previous)
    cat > "$DNSMASQ_POLICY_CONF" <<EOF
# Generated by $0 on $(date)
# Send all DNS queries to the upstream server
server=$UPSTREAM_DNS

# For each domain, add resolved IPs to the ipset
EOF
    for domain in $DOMAINS; do
        echo "ipset=/$domain/$IPSET_NAME" >> "$DNSMASQ_POLICY_CONF"
    done

    echo "dnsmasq configuration written to $DNSMASQ_POLICY_CONF"
}

# Ensure the custom routing table name is registered in rt_tables
configure_routing_table_name() {
    if ! grep -q "^$TABLE_ID[[:space:]]\+$TABLE_NAME$" "$RT_TABLES_FILE"; then
        echo "Adding entry '$TABLE_ID $TABLE_NAME' to $RT_TABLES_FILE"
        echo "$TABLE_ID $TABLE_NAME" >> "$RT_TABLES_FILE"
    else
        echo "Routing table name '$TABLE_NAME' already exists in $RT_TABLES_FILE"
    fi
}

# Add default route in the custom table via the Wi-Fi interface
add_custom_route() {
    # Check if route already exists in table $TABLE_NAME
    if ! ip route show table "$TABLE_NAME" | grep -q "default via $WIFI_GW dev $WIFI_IF"; then
        echo "Adding default route via $WIFI_IF ($WIFI_GW) to table $TABLE_NAME"
        ip route add default via "$WIFI_GW" dev "$WIFI_IF" table "$TABLE_NAME"
    else
        echo "Custom route already present in table $TABLE_NAME"
    fi
}

# Add iptables rule to mark packets whose destination IP is in the ipset
configure_iptables() {
    # Check if rule already exists in iptables (mangle table, OUTPUT chain)
    if ! iptables -t mangle -C OUTPUT -m set --match-set "$IPSET_NAME" dst -j MARK --set-mark "$FW_MARK" 2>/dev/null; then
        echo "Adding iptables rule to mark packets with mark $FW_MARK"
        iptables -t mangle -A OUTPUT -m set --match-set "$IPSET_NAME" dst -j MARK --set-mark "$FW_MARK"
    else
        echo "iptables rule already present"
    fi
}

# Add ip rule to use the custom routing table for marked packets
configure_iprule() {
    # Check if rule already exists
    if ! ip rule show | grep -q "fwmark $FW_MARK lookup $TABLE_NAME"; then
        echo "Adding ip rule: fwmark $FW_MARK lookup $TABLE_NAME"
        # Priority 32766 (after local table but before main) – adjust if needed
        ip rule add fwmark "$FW_MARK" priority 32766 table "$TABLE_NAME"
    else
        echo "ip rule already present"
    fi
}

# Restart dnsmasq to apply configuration
restart_dnsmasq() {
    echo "Restarting dnsmasq..."
    systemctl restart dnsmasq
    # Wait a moment for the service to settle
    sleep 2
    if systemctl is-active --quiet dnsmasq; then
        echo "dnsmasq restarted successfully."
    else
        echo "ERROR: dnsmasq failed to start. Check journalctl -u dnsmasq" >&2
        exit 1
    fi
}

# Display current status of the setup
show_status() {
    echo ""
    echo "========== STATUS =========="
    echo "ipset $IPSET_NAME contains:"
    ipset list "$IPSET_NAME" | head -n 10
    echo ""
    echo "iptables rule (mangle OUTPUT):"
    iptables -t mangle -L OUTPUT -v -n | grep "$IPSET_NAME" || echo "No matching iptables rule"
    echo ""
    echo "ip rules:"
    ip rule show | grep "fwmark $FW_MARK" || echo "No matching ip rule"
    echo ""
    echo "Custom routing table $TABLE_NAME:"
    ip route show table "$TABLE_NAME"
    echo ""
    echo "DNS configuration:"
    cat "$DNSMASQ_POLICY_CONF"
    echo "============================="
}

# --------------------- MAIN EXECUTION FLOW ---------------------
main() {
    check_root
    create_ipset
    configure_dnsmasq
    configure_routing_table_name
    add_custom_route
    configure_iptables
    configure_iprule
    restart_dnsmasq
    show_status
    echo ""
    echo "✅ Domain-based policy routing is now active."
    echo "💡 Note: The ipset will be populated dynamically as domains are resolved."
    echo "   Check with: sudo ipset list $IPSET_NAME"
}

# Run main function
main

echo "if you want remove policy, run this;"

function remove_policy(){
	sudo iptables -t mangle -D OUTPUT -m set --match-set google_ips dst -j MARK --set-mark 1
	sudo ip rule del fwmark 1 table mytable
	sudo ipset destroy google_ips
	sudo rm /etc/dnsmasq.d/99-policy-routing.conf
	sudo systemctl restart dnsmasq
}
